import { POPULAR_ARTISTS } from "./slugs";

export const ARTIST_BIOS: Record<string, string> = {
  "taylor-swift": "Pop's most meticulous storyteller, with a record-breaking era for every mood. Can you name her biggest songs?",
  "the-weeknd": "The architect of dark R&B who defined a decade of pop with brooding, cinematic hits.",
  "bad-bunny": "The king of Latin trap who made reggaeton a global phenomenon — how well do you know his catalogue?",
  "drake": "Hip-hop's most consistent chart-dominator, blending rap and R&B across a decade of smashes.",
  "ed-sheeran": "The acoustic pop savant who turned heartfelt storytelling into stadium anthems.",
  "ariana-grande": "A four-octave powerhouse who went from Disney to pop royalty in record time.",
  "post-malone": "The tattooed genre-bender who made melodic rap and rock feel like the same thing.",
  "billie-eilish": "The whisper-pop prodigy who rewrote what a teen pop star could sound like.",
  "justin-bieber": "The teen idol who grew up on camera and kept scoring hits along the way.",
  "eminem": "Detroit's fastest rapper and one of the best-selling artists of all time.",
  "rihanna": "Barbados-born pop force who pivoted between genres and built a cultural empire.",
  "kanye-west": "Polarising and genre-defining — his albums have left a permanent mark on hip-hop.",
  "bruno-mars": "A Honolulu-born showman who channels classic soul, funk, and pop into effortless hits.",
  "dua-lipa": "The Albanian-British disco revivalist who made the 80s feel brand new.",
  "olivia-rodrigo": "From Disney Channel to Grammy winner in one gut-punch of a debut album.",
  "doja-cat": "A shapeshifting rapper-singer who went viral, then went global.",
  "travis-scott": "Houston's biggest export — cinematic rap and festival spectacles that set the standard.",
  "sia": "The faceless icon whose soaring vocals have powered anthems for artists and herself alike.",
  "adele": "Britain's greatest voice of heartbreak, whose ballads outsell almost everyone on Earth.",
  "beyonce": "The most decorated artist in Grammy history, who has never once stood still.",
  "coldplay": "British rock veterans who evolved from post-Britpop into one of the world's biggest live acts.",
  "imagine-dragons": "Las Vegas rockers who crossed alternative rock into global pop territory.",
  "maroon-5": "LA's most durable pop-rock band, still scoring hits two decades after their debut.",
  "twenty-one-pilots": "The duo who blended rap, rock, and ukulele into a surprisingly massive fanbase.",
  "harry-styles": "Former One Direction heartthrob turned critically adored solo artist and fashion icon.",
  "lil-nas-x": "The internet's favourite provocateur, who turned a country-rap meme into a genuine career.",
  "shawn-mendes": "The Canadian singer-songwriter who grew up on Vine and grew into arena pop.",
  "selena-gomez": "Actress, activist, and pop star whose vulnerability has only made her more beloved.",
  "camila-cabello": "Fifth Harmony's breakout star who made Latin-pop crossover look easy.",
  "khalid": "El Paso's soft-spoken R&B voice, capturing the anxieties of growing up.",
  "halsey": "The alternative pop artist who never let the mainstream define what she could be.",
  "charlie-puth": "A classically trained producer who writes pop hooks with the precision of a metronome.",
  "sam-smith": "The Grammy-winning British soul singer with one of the most recognisable voices in pop.",
  "miley-cyrus": "One of pop's most fearless reinventors, from Hannah Montana to rock icon.",
  "sabrina-carpenter": "The Disney alumna who levelled up into one of pop's sharpest new voices.",
  "sza": "R&B's most emotionally raw star, with an album that stayed on the charts for years.",
  "peso-pluma": "The Mexican singer who made corridos tumbados a worldwide phenomenon.",
  "feid": "The Colombian artist blending reggaeton and urban sounds into a consistent string of hits.",
  "karol-g": "Colombia's reigning reggaeton queen and one of Latin music's most-streamed artists.",
  "rauw-alejandro": "Puerto Rico's smooth blend of reggaeton, R&B, and 80s synth-pop.",
  "j-balvin": "The Colombian reggaeton star who helped take Latin music global.",
  "daddy-yankee": "The godfather of reggaeton, with a career spanning underground clubs to billion-stream hits.",
  "ozuna": "One of the most-streamed Latin artists of all time, built on melodic reggaeton.",
  "bts": "The South Korean boy band who turned K-pop into a global cultural force.",
  "blackpink": "The four-member K-pop group who became the world's biggest girl group.",
  "one-direction": "The British-Irish boyband who defined a generation of pop fandom before going on hiatus.",
  "kendrick-lamar": "Compton's greatest poet, whose albums double as essays on race, identity, and power.",
  "juice-wrld": "Chicago's emo-rap prodigy whose legacy only grew after his passing at 21.",
  "xxxtentacion": "A turbulent artist whose emotional intensity left a lasting mark on a generation of rap.",
  "lil-uzi-vert": "Philadelphia's most eclectic rapper, hopping between genres with effortless charisma.",
};

export function getDailyArtistSlug(): string {
  const slugs = Object.keys(POPULAR_ARTISTS);
  const day = Math.floor(Date.now() / 86_400_000);
  return slugs[day % slugs.length];
}
