// Curated artist catalog ordered by all-time Spotify stream rank (kworb.net).
// Holds correctly-spelt names and slugs for the artists we care most about;
// the full ~3,000-artist directory lives in data/artists.json.
import { AUTOCOMPLETE_ARTISTS } from "./artistAutocompleteData";

export const ARTIST_CATALOG: Record<string, string> = {
  drake: "Drake",
  "taylor-swift": "Taylor Swift",
  "bad-bunny": "Bad Bunny",
  "the-weeknd": "The Weeknd",
  "justin-bieber": "Justin Bieber",
  "ariana-grande": "Ariana Grande",
  "travis-scott": "Travis Scott",
  "ed-sheeran": "Ed Sheeran",
  eminem: "Eminem",
  "kanye-west": "Kanye West",
  rihanna: "Rihanna",
  "billie-eilish": "Billie Eilish",
  "kendrick-lamar": "Kendrick Lamar",
  "post-malone": "Post Malone",
  "j-balvin": "J Balvin",
  future: "Future",
  "bruno-mars": "Bruno Mars",
  bts: "BTS",
  ozuna: "Ozuna",
  "juice-wrld": "Juice WRLD",
  coldplay: "Coldplay",
  "chris-brown": "Chris Brown",
  "nicki-minaj": "Nicki Minaj",
  "dua-lipa": "Dua Lipa",
  "david-guetta": "David Guetta",
  "lana-del-rey": "Lana Del Rey",
  "daddy-yankee": "Daddy Yankee",
  xxxtentacion: "XXXTENTACION",
  "imagine-dragons": "Imagine Dragons",
  "lil-wayne": "Lil Wayne",
  "rauw-alejandro": "Rauw Alejandro",
  "anuel-aa": "Anuel AA",
  "21-savage": "21 Savage",
  sza: "SZA",
  "karol-g": "Karol G",
  "lady-gaga": "Lady Gaga",
  khalid: "Khalid",
  "lil-baby": "Lil Baby",
  "maroon-5": "Maroon 5",
  "arijit-singh": "Arijit Singh",
  beyonce: "Beyoncé",
  maluma: "Maluma",
  feid: "Feid",
  "calvin-harris": "Calvin Harris",
  "myke-towers": "Myke Towers",
  "lil-uzi-vert": "Lil Uzi Vert",
  "j-cole": "J. Cole",
  "linkin-park": "Linkin Park",
  sia: "SIA",
  "young-thug": "Young Thug",
  "doja-cat": "Doja Cat",
  "peso-pluma": "Peso Pluma",
  shakira: "Shakira",
  "morgan-wallen": "Morgan Wallen",
  "shawn-mendes": "Shawn Mendes",
  farruko: "Farruko",
  "sam-smith": "Sam Smith",
  queen: "Queen",
  "one-direction": "One Direction",
  "metro-boomin": "Metro Boomin",
  adele: "Adele",
  "harry-styles": "Harry Styles",
  gunna: "Gunna",
  "arctic-monkeys": "Arctic Monkeys",
  "katy-perry": "Katy Perry",
  pritam: "Pritam",
  "tyler-the-creator": "Tyler, the Creator",
  "selena-gomez": "Selena Gomez",
  "ty-dolla-sign": "Ty Dolla $ign",
  "olivia-rodrigo": "Olivia Rodrigo",
  "nicky-jam": "Nicky Jam",
  "the-beatles": "The Beatles",
  halsey: "Halsey",
  "wiz-khalifa": "Wiz Khalifa",
  "playboi-carti": "Playboi Carti",
  "junior-h": "Junior H",
  pitbull: "Pitbull",
  "fuerza-regida": "Fuerza Regida",
  "frank-ocean": "Frank Ocean",
  "jay-z": "JAY-Z",
  "asap-rocky": "A$AP Rocky",
  "the-chainsmokers": "The Chainsmokers",
  marshmello: "Marshmello",
  "miley-cyrus": "Miley Cyrus",
  "sabrina-carpenter": "Sabrina Carpenter",
  "cardi-b": "Cardi B",
  "twenty-one-pilots": "Twenty One Pilots",
  "camila-cabello": "Camila Cabello",
  "michael-jackson": "Michael Jackson",
  "red-hot-chili-peppers": "Red Hot Chili Peppers",
  arcangel: "Arcángel",
  suicideboys: "$uicideboy$",
  onerepublic: "OneRepublic",
  avicii: "Avicii",
  "snoop-dogg": "Snoop Dogg",
  dababy: "DaBaby",
  kygo: "Kygo",
  "50-cent": "50 Cent",
  "natanael-cano": "Natanael Cano",
  "mac-miller": "Mac Miller",
  "romeo-santos": "Romeo Santos",
  sech: "Sech",
  quavo: "Quavo",
  "youngboy-never-broke-again": "YoungBoy Never Broke Again",
  "elton-john": "Elton John",
  "trippie-redd": "Trippie Redd",
  "the-neighbourhood": "The Neighbourhood",
  "zach-bryan": "Zach Bryan",
  "lil-peep": "Lil Peep",
  "manuel-turizo": "Manuel Turizo",
  tyga: "Tyga",
  tiesto: "Tiësto",
  "luke-combs": "Luke Combs",
  metallica: "Metallica",
  "alan-walker": "Alan Walker",
  "charlie-puth": "Charlie Puth",
  usher: "Usher",
  "don-toliver": "Don Toliver",
  "henrique-juliano": "Henrique & Juliano",
  "jason-derulo": "Jason Derulo",
  "justin-timberlake": "Justin Timberlake",
  "tate-mcrae": "Tate McRae",
  "kodak-black": "Kodak Black",
  "don-omar": "Don Omar",
  "bebe-rexha": "Bebe Rexha",
  "sean-paul": "Sean Paul",
  "kali-uchis": "Kali Uchis",
  blackpink: "BLACKPINK",
  jhayco: "JHAYCO",
  "demi-lovato": "Demi Lovato",
  "sebastian-yatra": "Sebastian Yatra",
  "a-boogie-wit-da-hoodie": "A Boogie Wit da Hoodie",
  "daft-punk": "Daft Punk",
  hozier: "Hozier",
  "luis-miguel": "Luis Miguel",
  "pop-smoke": "Pop Smoke",
  acdc: "AC/DC",
  "big-sean": "Big Sean",
  akon: "Akon",
  "ellie-goulding": "Ellie Goulding",
  "carin-leon": "Carín León",
  pink: "P!nk",
  "james-arthur": "James Arthur",
  "flo-rida": "Flo Rida",
  "tory-lanez": "Tory Lanez",
  nirvana: "Nirvana",
  migos: "Migos",
  "swae-lee": "Swae Lee",
  "fleetwood-mac": "Fleetwood Mac",
  "dj-snake": "DJ Snake",
  duki: "Duki",
  "britney-spears": "Britney Spears",
  bizarrap: "Bizarrap",
  radiohead: "Radiohead",
  diplo: "Diplo",
  "pharrell-williams": "Pharrell Williams",
  "polo-g": "Polo G",
  "marilia-mendonca": "Marília Mendonça",
  anitta: "Anitta",
  "lil-durk": "Lil Durk",
  "g-eazy": "G-Eazy",
  "the-kid-laroi": "The Kid LAROI",
  "black-eyed-peas": "Black Eyed Peas",
  "green-day": "Green Day",
  "justin-quiles": "Justin Quiles",
  "kid-cudi": "Kid Cudi",
  "gucci-mane": "Gucci Mane",
  "bob-marley": "Bob Marley",
  offset: "Offset",
  "daniel-caesar": "Daniel Caesar",
  "fall-out-boy": "Fall Out Boy",
  "shreya-ghoshal": "Shreya Ghoshal",
  "panic-at-the-disco": "Panic! At The Disco",
  "ne-yo": "Ne-Yo",
  "2-chainz": "2 Chainz",
  rosalia: "ROSALÍA",
  joji: "Joji",
  "stray-kids": "Stray Kids",
  "jorge-mateus": "Jorge & Mateus",
  "anirudh-ravichander": "Anirudh Ravichander",
  "lewis-capaldi": "Lewis Capaldi",
  morat: "Morat",
  camilo: "Camilo",
  nf: "NF",
  "charli-xcx": "Charli xcx",
  "roddy-ricch": "Roddy Ricch",
  partynextdoor: "PARTYNEXTDOOR",
  "bryson-tiller": "Bryson Tiller",
  "2pac": "2Pac",
  "ar-rahman": "A.R. Rahman",
  "lenny-tavarez": "Lenny Tavárez",
  "martin-garrix": "Martin Garrix",
  jul: "Jul",
  "mariah-carey": "Mariah Carey",
  gorillaz: "Gorillaz",
  logic: "Logic",
  "megan-thee-stallion": "Megan Thee Stallion",
  "christian-nodal": "Christian Nodal",
};


// Kept for backwards compatibility, prefer ARTIST_CATALOG in new code
export const POPULAR_ARTISTS = ARTIST_CATALOG;

const nameToSlug = Object.fromEntries(
  Object.entries(ARTIST_CATALOG).map(([slug, name]) => [name, slug]),
);

// The full directory keyed by URL slug. ARTIST_CATALOG covers ~200 artists;
// this covers the remaining ~2,800 so we never have to guess a name back out
// of its slug. Guessing loses accents and ampersands, which sends the wrong
// query to Spotify, "ba" resolved to Bad Bunny instead of bôa, "jo" to Elton
// John instead of Jão.
const directoryNameBySlug: Record<string, string> = Object.fromEntries(
  AUTOCOMPLETE_ARTISTS.filter((a) => a.slug).map((a) => [a.slug, a.name]),
);

export function slugToArtistName(slug: string): string {
  return (
    ARTIST_CATALOG[slug] ??
    directoryNameBySlug[slug] ??
    slug.replace(/-/g, " ")
  );
}

export function artistNameToSlug(name: string): string {
  return (
    nameToSlug[name] ??
    name
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "")
  );
}
